### ISSUE TITLE
<input type="color"...

### ISSUE THREAD

**Issue by LastGentlman** [LastGentlman/ETCH-A-SKETCH#1]
Unexpected display result prabably with CSS
```CSS
.color-picker {
    border-radius: 50%;
    height: 100px;
    width: 100px;
    overflow: hidden;
    border: none;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}
```
Unexpected output:
![Screenshot 2022-03-13 17:03:03](https://user-images.githubusercontent.com/90702483/158086499-530a5478-398e-4757-a250-9f1bfa0ac2d7.png)

**Comment by LastGentlman** [comment]
Solved in CSS adding the next code:
```CSS
input[type=color]::-webkit-color-swatch {
    border: none;
    border-radius: 50%;
  }
  
input[type=color]::-webkit-color-swatch-wrapper {
    border: none;
    padding: 0;
}
```
